Clang script fix

diff --git a/02-base b/02-base
--- a/02-base
+++ b/02-base
@@ -173,9 +173,10 @@ fi
 
 PKGS="filesystem linux-api-headers man-pages glibc tzdata zlib bzip2 file readline m4 bc binutils gmp mpfr mpc attr acl shadow gcc
 	pkg-config ncurses libcap sed psmisc iana-etc bison flex grep bash libtool gdbm gperf expat inetutils
-	perl perl-xml-parser intltool autoconf automake xz kmod gettext elfutils libffi openssl python3 coreutils"
+	perl perl-xml-parser intltool autoconf automake xz kmod gettext elfutils libffi openssl python3 coreutils
+	ca-certificates curl libarchive"
 
-CLANG_PKGS="libuv ca-certificates curl libarchive cmake llvm"
+CLANG_PKGS="libuv cmake llvm"
 
 CORE_PKGS="diffutils gawk findutils groff fuse2 grub less gzip iproute2 kbd libpipeline make patch man-db tar texinfo vim procps-ng
 	util-linux e2fsprogs sysklogd sysvinit eudev lfs-bootscripts linux-firmware mkinitramfs linux libtasn1 p11-kit
@@ -207,17 +208,17 @@ for pkg in $CLANG_PKGS; do
 	esac
 done
 
-for pkg in $CORE_PKGS do
+for pkg in $CORE_PKGS; do
 	case $pkg in
 		libuv|cmake|llvm|linux) runinchroot pkgin -i $pkg || die;;
-		*) runinclangchroot pkgin -i $pkg || { echo "WARN: $pkg could not be built with Clang."; runinchroot pkgin -i $pkg; } || die;;
+		*) runinclangchroot pkgin -i $pkg || { echo "WARN: $pkg could not be built with Clang." >> clang.errors; runinchroot pkgin -i $pkg; } || die;;
 	esac
 done
 
-for pkg in $ADDL_PKGS do
+for pkg in $ADDL_PKGS; do
 	case $pkg in
 		libuv|cmake|llvm) runinchroot pkgin -i $pkg || die;;
-		*) runinclangchroot pkgin -i $pkg || { echo "WARN: $pkg could not be built with Clang."; runinchroot pkgin -i $pkg; } || die;;
+		*) runinclangchroot pkgin -i $pkg || { echo "WARN: $pkg could not be built with Clang." >> clang.errors; runinchroot pkgin -i $pkg; } || die;;
 	esac
 done
 
