Split build process

diff --git a/02-base b/02-base
--- a/02-base
+++ b/02-base
@@ -58,7 +58,6 @@ EOF
 mount_pseudo() {
 	mkdir -p $LFS/{dev,run,proc,sys}
 	mount --bind /dev $LFS/dev
-	#mount -t devpts devpts $LFS/dev/pts -o gid=5,mode=620
 	mount -v --bind /dev/pts $LFS/dev/pts
 	mount -t proc proc $LFS/proc
 	mount -t sysfs sysfs $LFS/sys
@@ -110,6 +109,28 @@ runinchroot() {
 	return $retval
 }
 
+runinclangchroot() {
+	pushd $LFS &>/dev/null
+	mount_pseudo
+	mountbind_srcpkg
+	cp -L /etc/resolv.conf $LFS/etc/
+	chroot "$LFS" $ENVLFS -i \
+	    HOME=/root                  \
+	    TERM="$TERM"                \
+	    PS1='(lfs chroot) \u:\w\$ ' \
+	    CC=clang 					\
+	    CXX=clang++					\
+	    LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib \
+	    CFLAGS="-O2 -pipe" \
+		CXXFLAGS="${CFLAGS}"
+	    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin:/usr/local/sbin:/usr/local/bin $@
+	retval=$?
+	unmountbind_srcpkg
+	umount_pseudo
+	popd &>/dev/null
+	return $retval
+}
+
 interrupted() {
 	die "script $(basename $0) aborted!"
 }
@@ -152,11 +173,16 @@ fi
 
 PKGS="filesystem linux-api-headers man-pages glibc tzdata zlib bzip2 file readline m4 bc binutils gmp mpfr mpc attr acl shadow gcc
 	pkg-config ncurses libcap sed psmisc iana-etc bison flex grep bash libtool gdbm gperf expat inetutils
-	perl perl-xml-parser intltool autoconf automake xz kmod gettext elfutils libffi openssl python3 coreutils
-	diffutils gawk findutils groff fuse2 grub less gzip iproute2 kbd libpipeline make patch man-db tar texinfo vim procps-ng
+	perl perl-xml-parser intltool autoconf automake xz kmod gettext elfutils libffi openssl python3 coreutils"
+
+CLANG_PKGS="libuv cmake llvm"
+
+CORE_PKGS="diffutils gawk findutils groff fuse2 grub less gzip iproute2 kbd libpipeline make patch man-db tar texinfo vim procps-ng
 	util-linux e2fsprogs sysklogd sysvinit eudev lfs-bootscripts linux-firmware libarchive mkinitramfs linux libtasn1 p11-kit ca-certificates 
 	wget pkgutils libnl dbus libxml2 dhcpcd wpa_supplicant lzo lz4 squashfs-tools popt efivar pciutils efibootmgr libpng which freetype2 dosfstools grub-efi
 	curl ports httpup gpm libevent links mtools syslinux"
+
+ADDL_PKGS="fakeuname libaio nano openssh zstd rsync sudo libtirpc cpio git zfs"
 
 if [ ! -f $LFS/var/lib/pkg/db ]; then
 	lfs_dirs
@@ -171,6 +197,27 @@ for pkg in $PKGS; do
 	case $pkg in
 		filesystem|gcc|bash|perl|coreutils) runinchroot pkgin -i -ic $pkg || die;;
 		*) runinchroot pkgin -i $pkg || die;;
+	esac
+done
+
+for pkg in $CLANG_PKGS; do
+	case $pkg in
+		filesystem|gcc|bash|perl|coreutils) runinchroot pkgin -i -ic $pkg || die;;
+		*) runinchroot pkgin -i $pkg || die;;
+	esac
+done
+
+for pkg in $CORE_PKGS do
+	case $pkg in
+		libuv|cmake|llvm) runinchroot pkgin -i $pkg || die;;
+		*) runinclangchroot pkgin -i $pkg || { echo "WARN: $pkg could not be built with Clang."; runinchroot pkgin -i $pkg; } || die;;
+	esac
+done
+
+for pkg in $ADDL_PKGS do
+	case $pkg in
+		libuv|cmake|llvm) runinchroot pkgin -i $pkg || die;;
+		*) runinclangchroot pkgin -i $pkg || { echo "WARN: $pkg could not be built with Clang."; runinchroot pkgin -i $pkg; } || die;;
 	esac
 done
 
